APP_PORT: 9993
BASE_URL_PATH: "/cart-order-service"
DB_SSL_MODE: "disable"
DB_USER: root
DB_HOST: localhost
DB_PASSWORD: fatannajuda
DB_NAME: db_order
DB_DEBUG: true
DB_PORT: 5432

# Midtrans
MERCHANT_ID: G380575798
CLIENT_KEY: SB-Mid-client-5EiTk_oI-l39RY84
SERVER_KEY: SB-Mid-server-jz-9ZTjDo8yA-5kZCU6rgDNr